apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-dev

resources:
  - test-app-application.yaml
  - test-api-gw-application.yaml
#  - opensearch-application.yaml
#  - fluent-bit-application.yaml